### ISSUE TITLE
problems signing into Safari

### ISSUE THREAD

**Issue by michaelp6of7** [jigargosar/elm-simple-gtd#5]
Hi, I am unable to sign in with my iPhone 6 (iOS 10.3.3) using Safari. I click on the signin icon but nothing happens. Please let me know if there is a URL needed to sign-in on mobile.

Thanks,

Michael

**Comment by jigargosar** [comment]
Check
https://simplegtd.slack.com/archives/C6J6PV4G2/p1504846748000032
